--
-- Script was generated by Devart dbForge Studio 2022 for SQL Server, Version 6.3.9.0
-- Product home page: http://www.devart.com/dbforge/sql/studio
-- Script date 08/12/2022 4:58:52 am
-- Server version: 12.0.2000.8
--

SET DATEFORMAT ymd
SET ARITHABORT, ANSI_PADDING, ANSI_WARNINGS, CONCAT_NULL_YIELDS_NULL, QUOTED_IDENTIFIER, ANSI_NULLS, NOCOUNT ON
SET NUMERIC_ROUNDABORT, IMPLICIT_TRANSACTIONS, XACT_ABORT OFF
GO

INSERT bankon.bank_on.BlackListGroup(BlackListGroupId, Title, Expression, _Deleted, _case) VALUES ('604e95c7-6629-4eb7-8025-a549ea1feccc', N'Mobile', N'12345678900,12345678901,12345678902,12345678903,12345678904,12345678905', CONVERT(bit, 'False'), 1)
INSERT bankon.bank_on.BlackListGroup(BlackListGroupId, Title, Expression, _Deleted, _case) VALUES ('5a4d0ec1-3ade-48ee-8d36-f0d2032f6418', N'Domains', N'123,fakemail,notrealmail,bamboozler,definitelynotfake', CONVERT(bit, 'False'), 2)
GO