--
-- Script was generated by Devart dbForge Studio 2022 for SQL Server, Version 6.3.9.0
-- Product home page: http://www.devart.com/dbforge/sql/studio
-- Script date 08/12/2022 4:58:55 am
-- Server version: 12.0.2000.8
--

SET DATEFORMAT ymd
SET ARITHABORT, ANSI_PADDING, ANSI_WARNINGS, CONCAT_NULL_YIELDS_NULL, QUOTED_IDENTIFIER, ANSI_NULLS, NOCOUNT ON
SET NUMERIC_ROUNDABORT, IMPLICIT_TRANSACTIONS, XACT_ABORT OFF
GO

INSERT bankon.bank_on.FinanceRequestStatus(FinanceRequestStatusId, Title, Description, _case, _Deleted) VALUES ('6ff3343b-aa91-4641-8ab2-0d889aa2d054', N'Denied', N'Financing request has been denied', 3, CONVERT(bit, 'False'))
INSERT bankon.bank_on.FinanceRequestStatus(FinanceRequestStatusId, Title, Description, _case, _Deleted) VALUES ('24847d35-3c12-421f-83d5-187ac69d33bc', N'Pending', N'Initial status for requests', 0, CONVERT(bit, 'False'))
INSERT bankon.bank_on.FinanceRequestStatus(FinanceRequestStatusId, Title, Description, _case, _Deleted) VALUES ('af515a52-ff82-41e8-864c-bbd823202826', N'Submitted', N'Status for request that have applied', 1, CONVERT(bit, 'False'))
INSERT bankon.bank_on.FinanceRequestStatus(FinanceRequestStatusId, Title, Description, _case, _Deleted) VALUES ('c15d01ac-c05f-46de-aaec-e7895060e5bd', N'Approved', N'Request has been approved for financing', 2, CONVERT(bit, 'False'))
GO